on:
  schedule:
    - cron: '0 8 1 1-12 *'
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::googlesheets4
            any::data.table
            any::plyr
            any::dplyr
            any::rvest
            any::sqldf
            any::stringr
            any::progress
            any::httr
            any::pdftools
            any::tidyverse
            any::arrow

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Import data
        run: Rscript -e 'source("import-data.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add townships-united.rds
          git add townships-united.csv
          git add townships-united.parquet
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
